config/routes.rb
Rails.application.routes.draw do
  get 'dashboards/home'
  get 'dashboards/index'
  post 'dashboards/search_result'
  root "dashboards#home"
  resources :dashboards
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bot.rb
class Bot < ApplicationRecord

    # def self.find_user number, words
    #   CLIENT.search(words, lang: "en").take(number).each { |t|
    #     User.create(name: t.user.screen_name, tweet_id: t.id.to_s)
    #     CLIENT.update(Bot.respond(t.user.screen_name), in_reply_to_status_id: t.id)
    #   }
    # end

    def self.search_words number, words
      # CLIENT.search(words, lang: "en").first.text

        CLIENT.search(words, lang: "en").take(number)

    end




    # def self.respond
    #   name "@" + name + " " + Response.order_by_rand.first.message
    # end

end

app/models/response.rb
class Response < ApplicationRecord
end

app/models/result.rb
class Result < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
  # def home
  #   @search_key = (params[:search])
  #   number = 10
  #   search_result(number, @search_key)
  # end

  def index
    @results = Result.paginate(:page => params[:page], :per_page => 10)
  end

  def search_result
    number = 10
    search_key = params[:search]
    @data = Bot.search_words number, "#"+search_key
      @data.each do |data|
        twitter_id = data.id
        unless Result.find_by(twitter_id: twitter_id).present?
          tweet = data.text
          Result.create(twitter_id: twitter_id, tweet: tweet, search_key: search_key)
        end
      end
      puts "data==========>",@data
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboards_helper.rb
module DashboardsHelper
end

app/views/dashboards/_search_result.html.erb
<% @data.each do |tweet|%>
<%= tweet.text%>
<br>
<%end%>

app/views/dashboards/home.html.erb
<h1>Dashboards#home</h1>
<%= form_tag dashboards_search_result_path,:remote => true, :method => 'post' do %>
  <p>
    <%= text_field_tag :search, params[:search] %>
    <%= submit_tag "Search & Save", :name => nil %>
  </p>
<% end %>

<div class="twitter-search-results"></div>

app/views/dashboards/index.html.erb
<h1><center>Dashboards#index</center></h1>

<div><%= link_to :HOME, root_url, class: "btn btn-success" %></div>
<div class="container">
<table class="table table-bordered">
  <thead>
    <tr class="header">
      <th>Twitter Id</th>
      <th>Tweet</th>
      <th>Search_key</th>
    </tr>
   </thead>
   <tbody>
    <% @results.each do |r| %>
      <tr>
        <td><%= r.twitter_id %></td>
        <td><%= r.tweet %></td>
        <td><%= r.search_key %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= will_paginate @results %>
</div>

app/views/dashboards/search_result.js.erb
$(".twitter-search-results").html("<%= escape_javascript(render partial: 'search_result.html.erb') %>")

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TwitterApp</title>
    <meta charset="utf-8">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'true' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'true' %>
    


  </head>

  <body>
    <%= yield %>
  </body>
</html>